name: Release Aragomodoro
on:
  push:
    branches:
      - main

    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'
      - 'img/**'
      - LICENSE

jobs:
  release:
    name: Generate Release Aragomodoro
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1 
        id: tag_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          TAG_PREFIX: v
          PRERELEASE: true

      - name: Create Release Aragomodoro
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: ${{ steps.tag_version.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      
      - name: Install dependencies
        run: apt update && apt install -y libasound2-dev pkg-config

      - name: Build Aragomodoro binary
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/aragomodoro ./cmd

      - name: Upload Linux binary to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: build/aragomodoro
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
